stages:
  - test
  - build

test:
  stage: test
  image: golang:1.17
  script:
   - go test .
  rules:
    - changes:
        - "**/*.go"
        - "go.mod"
        - "go.sum"
      when: always
  tags:
    - netology

build:
  stage: build
  image: docker:latest
  script:
   - docker build .
  tags:
    - netology
